[package]
name = "mausritter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy_prng = "0.1.0"
bevy_rand = "0.3.0"
rand_core = "0.6.4"
